#!/bin/python3

import sys

l = {0: 1, 1: 2}

def fib(n):
    if n not in l:
        l[n] = fib(n-1) + fib(n-2)
    return [n]

for _ in range(int(input())):
    n = int(input())
    s = 0
    i = 0
    while(fib(i)<=n):
        if fib(i)%2 == 0:
            s += fib(i)
        i = i+1
    print(s)
        
